= IT-Hub Braunschweig Backend

image:https://travis-ci.org/stevenschwenke/ithubbs_backend.svg?branch=master["Build Status", link="https://travis-ci.org/stevenschwenke/ithubbs_backend"]

This is the backend to http://www.ithubbs.de[ithubbs.de]

== Setup PCF
Only once, set "User Provided Environment Variables":

|===
|key |value
|JBP_CONFIG_OPEN_JDK_JRE | jre: { version: 10.0.2_13 }
|SPRING_PROFILES_ACTIVE | test
|jwt.secret | A long-enough string, for example this one because its really long and so secure. Yeay! This is a really long string.
|===


== Deploy to PCF
For every deployment, do:

1. Create jar with all dependencies

    gradle bootJar

1. Login to PCF

    cf login -a api.run.pivotal.io

1. Push

    cf push -f manifest_test.yml

== Local development: H2 console
To access the local database, visit http://localhost:8090/ithubbs/console with

* JDBC URL: jdbc:h2:./h2/ithubbsh2db;
* User Name: sa
* empty password

== Operation
This section is about some aspects concerning the operation of this software. It was developed to run on https://pivotal.io/platform[Pivotal Cloud Foundry] which is why this manual focuses on this platform.

=== Running on PCF

The following configuration is sufficient to run on Pivotal Cloudfoundry:

* (Process "task" can be configured to have 64 MB of both memory and disk because it has 0 instances. The following values are for process "web".)
* instances: 1
* Memory Allocated: 1 GB
* Disk Allocated: 512 MB
* PostgreSQL with free plan
* Price per month on Pivotal Cloudfoundry: *< $21,60*

=== Database Backup
* ElephantSQL, a PostgreSQL as-a-service provided by Pivotal Cloudfoundry, has https://www.elephantsql.com/docs/backups.html[automated backups]. There will be a daily database backup.